<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TargetPlatformDisplayName>Windows</TargetPlatformDisplayName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>Assets\luming.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\owl.png" />
    <Resource Include="Assets\luming-logo.png" />
    <Resource Include="Assets\deer-drink-1.png" />
    <Resource Include="Assets\deer-drink-2.png" />
    <Resource Include="Assets\deer-drink-3.png" />
  </ItemGroup>
</Project>
