<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <TargetPlatformDisplayName>Windows</TargetPlatformDisplayName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon />
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="Assets\owl.png" />
  </ItemGroup>
</Project>
